### ISSUE TITLE
Request for help: how can I generate 'upd_id_final.txt' in the Imputation code?

### ISSUE THREAD

**Issue by YuxinZhaoooooo** [MartinsAdrielle/Imputation#1]
Hi Martin, @MartinsAdrielle 

Thank you for your contribution to the imputation code. I found it rather helpful in my research. 

I have encountered a problem and wanna ask for your kind help. I can't find your e-mail address, so I have got to request your kind help here.

The question is: How can generate my 'upd_id_final.txt' in my own case? i.e., 'upd_id_final.txt' in line 144 of 'Imputation code': plink2 --bfile imp_semindels --update-ids ../upd_id_final.txt --make-bed --out imputado_ID.

Thanks a lot for your kind help.

Best,
Yuxin.

**Comment by YuxinZhaoooooo** [comment]
> Hi Martin, @MartinsAdrielle
> 
> Thank you for your contribution to the imputation code. I found it rather helpful in my research.
> 
> I have encountered a problem and wanna ask for your kind help. I can't find your e-mail address, so I have got to request your kind help here.
> 
> The question is: How can generate my 'upd_id_final.txt' in my own case? i.e., 'upd_id_final.txt' in line 144 of 'Imputation code': plink2 --bfile imp_semindels --update-ids ../upd_id_final.txt --make-bed --out imputado_ID.
> 
> Thanks a lot for your kind help.
> 
> Best, Yuxin.

I've solved the problem. For the latecomers convenience, refer to https://www.biostars.org/p/171557/
The key is to generate a text file with the 2 specific columns, i.e., chr:pos and rsID.

**Comment by MartinsAdrielle** [comment]
Hi Yuzin,

Sorry for the delay in the response, this file is made based on the new ID you want to put in your samples, sometimes after imputation, the IDs can be unformatted (if this has not happened, you can skip this step)
This file is made from the original .fam file and should be a tab-delimited file with the columns:
old FID | old IID | new FID | new IID

Hope it helps in your research
Best, Adrielle

**Comment by YuxinZhaoooooo** [comment]
> 
Hi Adrielle，

Thank you for your reply. Your code inspired me a lot. In my case, it's the SNP IDs instead of the sample IDs that became unformatted after imputation. Therefore, I got them updated using --update-name instead. 

Thank you very much.

Best, 
Yuxin
